services:
  rust:
    build:
      context: ./Docker/rust
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
  mariadb:
    build:
      context: ./Docker/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
